sudo: required
services:
    - docker

before_install:
    - docker build -t jollycola/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run jollycola/react-test npm test -- --coverage

after_success:
    - docker build -t jollycola/complex-client ./client
    - docker build -t jollycola/complex-nginx ./nginx
    - docker build -t jollycola/complex-server ./server
    - docker build -t jollycola/complex-worker ./worker
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take the images and push to docker hub
    - docker push jollycola/complex-client
    - docker push jollycola/complex-nginx
    - docker push jollycola/complex-server
    - docker push jollycola/complex-worker
